### ISSUE TITLE
[Request] Fix some of the existing IntelliJ Javadoc requests

### ISSUE THREAD

**Issue by Michael-Ziluck** [ArtsiomCh/JDCleanRead#3]
This plugin seems really neat. A lot of the content in it I would expect IntelliJ to have by default, but this plugin is a fantastic alternative.

I know for a fact that myself and some others on the various development teams I work on would immediately purchase licenses for this software if you were to fix one or both of these issues as part of the plugin:

https://youtrack.jetbrains.com/issue/IDEA-114661
https://youtrack.jetbrains.com/issue/IDEA-121723

**Comment by ArtsiomCh** [comment]
Hi Michael! 
Both mentioned issues are out of the scope fo this plugin: make Javadoc more readable without modifying it.
Nevertheless, that could be a could idea for another plugin. Will explore when I have extra time. 
Thank you!

PS Also, let's wait for 2019.3 where JetBrains team promised to focus on fixing the most voted issue in the bug tracker.
